-- VINTAGE v30: roles + Minecraft player statistics. No v29 whitelist bridge/RCON sync.
-- Apply this migration to a fresh VINTAGE database.
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role = ANY (ARRAY['user'::text,'admin'::text,'streamer'::text]));

CREATE TABLE IF NOT EXISTS public.player_stats (profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,minecraft_uuid text,minecraft_nickname text,play_time_ticks bigint NOT NULL DEFAULT 0,deaths bigint NOT NULL DEFAULT 0,player_kills bigint NOT NULL DEFAULT 0,mob_kills bigint NOT NULL DEFAULT 0,is_online boolean NOT NULL DEFAULT false,last_seen_at timestamptz,synced_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS player_stats_play_time_idx ON public.player_stats(play_time_ticks DESC);
CREATE INDEX IF NOT EXISTS player_stats_last_seen_idx ON public.player_stats(last_seen_at DESC);
ALTER TABLE public.player_stats ENABLE ROW LEVEL SECURITY; REVOKE ALL ON public.player_stats FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_set_role(target_user uuid,new_role text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF; IF new_role NOT IN ('user','admin','streamer') THEN RAISE EXCEPTION 'Invalid role'; END IF; UPDATE public.profiles SET role=new_role WHERE id=target_user; IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF; END; $$;
REVOKE ALL ON FUNCTION public.admin_set_role(uuid,text) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.admin_set_role(uuid,text) TO authenticated;

CREATE SCHEMA IF NOT EXISTS private; CREATE TABLE IF NOT EXISTS private.stats_bridge_config(token_hash text NOT NULL); REVOKE ALL ON private.stats_bridge_config FROM PUBLIC,anon,authenticated; INSERT INTO private.stats_bridge_config(token_hash) SELECT 'd8857854af8cbf96ddc3fc2523d45223366d74713f6ab45e44585c6f9eebacfe' WHERE NOT EXISTS (SELECT 1 FROM private.stats_bridge_config);

CREATE OR REPLACE FUNCTION public.bridge_sync_player_stats(p_token text,p_minecraft_uuid text,p_minecraft_nickname text,p_play_time_ticks bigint,p_deaths bigint,p_player_kills bigint,p_mob_kills bigint,p_is_online boolean,p_last_seen_at timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE v_profile uuid; BEGIN IF encode(digest(p_token,'sha256'),'hex') <> (SELECT token_hash FROM private.stats_bridge_config LIMIT 1) THEN RAISE EXCEPTION 'Invalid bridge token'; END IF; SELECT p.id INTO v_profile FROM public.profiles p WHERE lower(p.minecraft_nickname)=lower(p_minecraft_nickname) LIMIT 1; IF v_profile IS NULL THEN SELECT wa.user_id INTO v_profile FROM public.whitelist_applications wa WHERE lower(wa.minecraft_nickname)=lower(p_minecraft_nickname) AND wa.status='approved' ORDER BY wa.created_at DESC LIMIT 1; END IF; IF v_profile IS NULL THEN RETURN false; END IF; INSERT INTO public.player_stats(profile_id,minecraft_uuid,minecraft_nickname,play_time_ticks,deaths,player_kills,mob_kills,is_online,last_seen_at,synced_at,updated_at) VALUES(v_profile,p_minecraft_uuid,p_minecraft_nickname,GREATEST(COALESCE(p_play_time_ticks,0),0),GREATEST(COALESCE(p_deaths,0),0),GREATEST(COALESCE(p_player_kills,0),0),GREATEST(COALESCE(p_mob_kills,0),0),COALESCE(p_is_online,false),p_last_seen_at,now(),now()) ON CONFLICT(profile_id) DO UPDATE SET minecraft_uuid=EXCLUDED.minecraft_uuid,minecraft_nickname=EXCLUDED.minecraft_nickname,play_time_ticks=EXCLUDED.play_time_ticks,deaths=EXCLUDED.deaths,player_kills=EXCLUDED.player_kills,mob_kills=EXCLUDED.mob_kills,is_online=EXCLUDED.is_online,last_seen_at=EXCLUDED.last_seen_at,synced_at=now(),updated_at=now(); RETURN true; END; $$;
REVOKE ALL ON FUNCTION public.bridge_sync_player_stats(text,text,text,bigint,bigint,bigint,bigint,boolean,timestamptz) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.bridge_sync_player_stats(text,text,text,bigint,bigint,bigint,bigint,boolean,timestamptz) TO anon;

CREATE OR REPLACE FUNCTION public.get_public_player_stats(p_user_id uuid) RETURNS TABLE(id uuid,username text,minecraft_nickname text,role text,whitelist_approved boolean,play_time_ticks bigint,deaths bigint,player_kills bigint,mob_kills bigint,is_online boolean,last_seen_at timestamptz,created_at timestamptz) LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT p.id,p.username,COALESCE(ps.minecraft_nickname,p.minecraft_nickname),p.role,EXISTS(SELECT 1 FROM public.whitelist_applications wa WHERE wa.user_id=p.id AND wa.status='approved'),COALESCE(ps.play_time_ticks,0),COALESCE(ps.deaths,0),COALESCE(ps.player_kills,0),COALESCE(ps.mob_kills,0),COALESCE(ps.is_online,false),ps.last_seen_at,p.created_at FROM public.profiles p LEFT JOIN public.player_stats ps ON ps.profile_id=p.id WHERE p.id=p_user_id; $$;
REVOKE ALL ON FUNCTION public.get_public_player_stats(uuid) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.get_public_player_stats(uuid) TO anon,authenticated;

CREATE OR REPLACE FUNCTION public.get_top_players(p_limit integer DEFAULT 20) RETURNS TABLE(id uuid,username text,minecraft_nickname text,role text,play_time_ticks bigint,deaths bigint,player_kills bigint,mob_kills bigint,is_online boolean,last_seen_at timestamptz) LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT p.id,p.username,COALESCE(ps.minecraft_nickname,p.minecraft_nickname),p.role,COALESCE(ps.play_time_ticks,0),COALESCE(ps.deaths,0),COALESCE(ps.player_kills,0),COALESCE(ps.mob_kills,0),COALESCE(ps.is_online,false),ps.last_seen_at FROM public.profiles p LEFT JOIN public.player_stats ps ON ps.profile_id=p.id WHERE EXISTS(SELECT 1 FROM public.whitelist_applications wa WHERE wa.user_id=p.id AND wa.status='approved') ORDER BY COALESCE(ps.play_time_ticks,0) DESC,p.created_at ASC LIMIT GREATEST(1,LEAST(COALESCE(p_limit,20),100)); $$;
REVOKE ALL ON FUNCTION public.get_top_players(integer) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.get_top_players(integer) TO anon,authenticated;
